version: "2"

services:

  dev:
    build: .
    volumes:
      - .:/code
    working_dir: /code
    command: php test.php
    environment:
      - SNOWFLAKE_HOST
      - SNOWFLAKE_PORT
      - SNOWFLAKE_USER
      - SNOWFLAKE_PASSWORD
      - SNOWFLAKE_DATABASE
      - SNOWFLAKE_WAREHOUSE
